import '../../styles/globals.css'
import React  from "react";
import {Inter} from "next/font/google";
import Layout from "./(components)/(shared)/(layout)/Layout";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface IProps {
    children: React.ReactNode;
}

const inter = Inter({subsets: ['latin']});

export default function RootLayout({children}: IProps) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Layout>
                    {children}
                </Layout>
            </body>
        </html>
    )
}
